### ISSUE TITLE
"registry" example has error in flag

### ISSUE THREAD

**Issue by vielmetti** [acorn-io/library#15]
```
> ./acorn run -d host.domain.ts.net:registry acorn-io/library/registry:2.8.1
Error: unknown shorthand flag: 'd' in -d
```

Taken from the example at 

https://github.com/acorn-io/library/blob/ea4ba8ede9d712113834b9fd932e5d343331df55/registry/README.md?plain=1#L17

(I suspect the flag shorthand has been updated, but I don't know to what!)

**Comment by cloudnautique** [comment]
It's now `-p` we need to update the README. Thanks for point it out, and sorry for the confusion.

**Comment by cloudnautique** [comment]
updated readme in #16
